# Generated by Django 5.0.6 on 2024-05-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistExplorer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artists',
            name='id',
        ),
        migrations.AddField(
            model_name='artists',
            name='ArtistId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
