# Generated by Django 5.0.3 on 2024-05-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistExplorer', '0003_artists_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='Genres',
            new_name='Followers',
        ),
    ]
