# Generated by Django 5.0.6 on 2024-05-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistExplorer', '0004_rename_genres_artists_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
